name: Build
on:
  pull_request:
    branches:
      - combined-sdk
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version:
          - '3.8'
          - '3.11'
          - '3.13'
    name: Build with Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install tox-gh-actions
      - name: All Tests
        if: startsWith(github.head_ref, 'codegen-release')
        env:
          JWT_CONFIG_BASE_64: ${{ secrets.JWT_CONFIG_BASE_64 }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
          ENTERPRISE_ID: ${{ secrets.ENTERPRISE_ID }}
          BOX_FILE_REQUEST_ID: ${{ secrets.BOX_FILE_REQUEST_ID }}
          BOX_EXTERNAL_USER_EMAIL: ${{ secrets.BOX_EXTERNAL_USER_EMAIL }}
          BOX_EXTERNAL_USER_ID: ${{ secrets.BOX_EXTERNAL_USER_ID }}
          APP_ITEM_ASSOCIATION_FILE_ID: ${{ secrets.APP_ITEM_ASSOCIATION_FILE_ID }}
          APP_ITEM_ASSOCIATION_FOLDER_ID: ${{ secrets.APP_ITEM_ASSOCIATION_FOLDER_ID }}
          WORKFLOW_FOLDER_ID: ${{ secrets.WORKFLOW_FOLDER_ID }}
          APP_ITEM_SHARED_LINK: ${{ secrets.APP_ITEM_SHARED_LINK }}
          SLACK_AUTOMATION_USER_ID: ${{ secrets.SLACK_AUTOMATION_USER_ID }}
          SLACK_ORG_ID: ${{ secrets.SLACK_ORG_ID }}
          SLACK_PARTNER_ITEM_ID: ${{ secrets.SLACK_PARTNER_ITEM_ID }}
        run: |
          tox
      - name: Smoke Tests
        if: "!startsWith(github.head_ref, 'codegen-release')"
        env:
          JWT_CONFIG_BASE_64: ${{ secrets.JWT_CONFIG_BASE_64 }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
          ENTERPRISE_ID: ${{ secrets.ENTERPRISE_ID }}
        run: |
          tox -- test/box_sdk_gen/test/auth.py test/box_sdk_gen/test/files.py test/box_sdk_gen/test/downloads.py test/box_sdk_gen/test/uploads.py