name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  pull_request:
    branches:
      - 'main'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT" 
    - name: step hello
      run: |
        echo hello    
    # steps:
    #   - run: |
    #       echo "Hello ${{ github.event.inputs.name }}!"
    #       echo "- in ${{ github.event.inputs.home }}!"