# A GitHub action that notifies the developer
# changelog repository of any new releases.

name: Notify changelog

on:
  # Only trigger for a full release,
  # ignoring pre-releases and drafts
  release:
    types:
      - released

jobs:
  notify:
    # This job can run on the latest Ubuntu
    # and it should not take more than 3 minutes
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      # There's really only 1 step, and i
      - name: Notify changelog of new release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: box/box-developer-changelog
          event-type: new-release-note
          client-payload: '{"ref": "${{ github.ref }}", "repository": "${{github.repository}}", "labels": "sdks,python", "repo_display_name": "Box Python SDK"}'
